package com.dicoding.picodiploma.kamenrider;

import java.util.ArrayList;

public class KamenRiderData {
    public static String[][] data = new String[][]{
            {"Kamen Rider Kuga", "Kamen Rider Heisei 1st", "https://vignette.wikia.nocookie.net/kamenrider/images/f/fc/Kuuga_Logo.png/revision/latest?cb=20180807133234","https://vignette.wikia.nocookie.net/kamenrider/images/a/a1/Kuuga_Poster.png/revision/latest?cb=20180807135233","January 30, 2000-January 21, 2001", "49 Episodes", "Toei Company","Kamen Rider Kuuga (仮面ライダークウガ Kamen Raidā Kūga, Masked Rider Kuuga) is a Japanese tokusatsu television series. It is the tenth installment of the popular Kamen Rider Series of tokusatsu shows and the first of the series to air entirely in the Heisei period. It was a joint collaboration between Ishimori Productions and Toei, and was shown on TV Asahi from January 30, 2000 to January 21, 2001. Kamen Rider Kuuga is the first Kamen Rider Series to be broadcast in widescreen format (albeit presented in a letterbox format). The catchphrase for the series is \"A New Hero, A New Legend\"."},
            {"Kamen Rider 555", "Kamen Rider Heisei 4th", "https://vignette.wikia.nocookie.net/kamenrider/images/6/63/Faiz_Logo.png/revision/latest?cb=20180807133612","https://vignette.wikia.nocookie.net/kamenrider/images/9/9c/Faiz_Poster.png/revision/latest?cb=20180807151100", "January 26, 2003-January 18, 2004", "50 Episodes","Toei Company", "Kamen Rider 555 (仮面ライダー555（ファイズ） Kamen Raidā Faizu, Kamen Rider Faiz, Masked Rider Φ's, Phi's, or Faiz) is a Japanese tokusatsu television series. It is the 13th installment in the Kamen Rider Series. It is a joint collaboration between Ishimori Productions and Toei, and was broadcast on TV Asahi from January 26, 2003 to January 18, 2004. It aired alongside Bakuryu Sentai AbarangerIcon-crosswiki for Super Hero Time 2003. The catchphrase for the series is \"Racing Instinct\" (疾走する本能 Shissō Suru Honnō)."},
            {"Kamen Rider Blade", "Kamen Rider Heisei 5th", "https://vignette.wikia.nocookie.net/kamenrider/images/3/3f/Blade_Logo.png/revision/latest?cb=20180807133814","https://vignette.wikia.nocookie.net/kamenrider/images/c/ca/Blade_Poster.png/revision/latest?cb=20180807151438", "January 25, 2004-January 23, 2005", "49 Episodes","Toei Company", "Kamen Rider Blade (仮面ライダーブレイド Kamen Raidā Bureido, Masked Rider ♠ or Blade), is a Japanese tokusatsu superhero television series. It is the fourteenth installment in the Kamen Rider Series. It aired on TV Asahi from January 25, 2004 to January 23, 2005. It aired alongside Tokusou Sentai DekarangerIcon-crosswiki for Super Hero Time 2004. It is a joint collaboration between Ishimori Productions and Toei. It is also the last Kamen Rider series to run on 60 fps. Along with the standard insect motif of the Kamen Rider series, Kamen Rider Blade also uses a playing card motif. Each Rider is assigned one of the suits from a deck of cards. The series catchphrases are \"Now your power is at its peak.\" (今、その力が展開する Ima, sono chikara ga tenkai suru) and \"Take the trump card of fate!\" (運命の切札をつかみ取れ! Unmei no kirifuda o tsukamitore!)."},
            {"Kamen Rider Kabuto", "Kamen Rider Heisei 7th", "https://vignette.wikia.nocookie.net/kamenrider/images/5/56/Kabuto_logo.png/revision/latest?cb=20180807133912","https://vignette.wikia.nocookie.net/kamenrider/images/e/e7/Kabuto_Poster.png/revision/latest?cb=20180807152824", "January 29, 2006-January 21, 2007", "49 Episodes","Toei Company", "Kamen Rider Kabuto (仮面ライダーカブト Kamen Raidā Kabuto, Masked Rider Kabuto) is a Japanese tokusatsu superhero television series. It is the sixteenth installment in the popular Kamen Rider Series of tokusatsu programs. It is a joint collaboration between Ishimori Productions and Toei. The series was broadcast on TV Asahi. The first episode aired on January 29, 2006, and with the final episode airing on January 21, 2007, completing the series with 49 episodes. It aired alongside GoGo Sentai BoukengerIcon-crosswiki for Super Hero Time 2006. The series represents the 35th anniversary of the Masked Rider Series, as indicated by a notice at the beginning of the pilot episode reading, in Japanese, \"Kamen Rider 35th Anniversary Production.\" Kamen Rider Kabuto is the first Kamen Rider Series to be broadcast in high-definition format."},
            {"Kamen Rider W", "Kamen Rider Heisei 11th", "https://vignette.wikia.nocookie.net/kamenrider/images/2/27/W_Title.png/revision/latest?cb=20181207151824","https://vignette.wikia.nocookie.net/kamenrider/images/6/68/W_Poster.png/revision/latest?cb=20180807151943", "September 6, 2009-August 29, 2010", "49 Episodes","Toei Company", "Kamen Rider W (仮面ライダーＷ（ダブル） Kamen Raidā Daburu) is a 2009-2010 Japanese tokusatsu drama, the eleventh series in the Heisei period run of the Kamen Rider Series. It premiered following the finale of Kamen Rider Decade on September 6, 2009,[1] and aired alongside Samurai Sentai ShinkengerIcon-crosswiki in TV Asahi's Super Hero Time programming block. Following Shinkenger's finale, it aired alongside Tensou Sentai GoseigerIcon-crosswiki, until W concluded on August 29, 2010. The series is described as the \"Heisei Kamen Rider 10th Anniversary Project: Fall Campaign\" (平成仮面ライダー10周年プロジェクト 秋の陣 Heisei Kamen Raidā Jusshūnen Purojekuto: Aki no Jin). The catchphrases for the series are \"We are the two-in-one Kamen Rider\" (俺たちは/僕たちは、二人で一人の仮面ライダーさ Ore-tachi wa/Boku-tachi wa, futari de hitori no Kamen Raidā sa) and \"This clinches it!\" (これで決まりだ! Kore de kimari da!)."},
            {"Kamen Rider Gaim", "Kamen Rider Heisei 15th", "https://vignette.wikia.nocookie.net/kamenrider/images/b/b3/Gaim_logo.png/revision/latest?cb=20180807134650","https://vignette.wikia.nocookie.net/kamenrider/images/f/f6/Gaim_Poster.png/revision/latest?cb=20180807152341", "October 6, 2013 - September 28, 2014", "47 Episodes","Toei Company", "Kamen Rider Gaim (仮面ライダー鎧武ガイム Kamen Raidā Gaimu) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series, it is the fifteenth series in the Heisei period run and the twenty-fourth series overall. Toei registered the copyright and trademark of the series, which started on October 6, 2013, joining Zyuden Sentai KyoryugerIcon-crosswiki in the Super Hero Time line-up three weeks after the finale of Kamen Rider Wizard. After Kyoryuger concluded on February 9, 2014, Kamen Rider Gaim was joined in the Super Hero Time lineup with Ressha Sentai ToQgerIcon-crosswiki. After the finale of Kamen Rider Gaim, Kamen Rider Drive joined ToQger on the Super Hero Time block. The catchphrase for the series are \"It's a Rider Warring (Sengoku) era.\" (ライダー戦国時代。 Raidā Sengoku Jidai) and \"How would you use your power?\" (キミはこの力どう使う? Kimi wa kono chikara dō tsukau)."},
            {"Kamen Rider Build", "Kamen Rider Heisei 19th", "https://vignette.wikia.nocookie.net/kamenrider/images/f/f8/BUILD_LOGO.png/revision/latest?cb=20180807134842","https://vignette.wikia.nocookie.net/kamenrider/images/d/d9/Build_Poster.png/revision/latest?cb=20180807151415", "September 3, 2017 - August 26, 2018", "49 Episodes","Toei Company", "Kamen Rider Build (仮面ライダービルド Kamen Raidā Birudo) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series. It is the nineteenth and final series for a full Heisei period run and the twenty-eighth series overall. The series started on September 3, 2017, joining Uchu Sentai KyurangerIcon-crosswiki in the Super Hero Time line-up after the finale of Kamen Rider Ex-Aid. After Kyuranger concluded on February 4, 2018, the series was joined by Kaitou Sentai Lupinranger VS Keisatsu Sentai PatrangerIcon-crosswiki in the Super Hero Time line-up. After the finale of Kamen Rider Build, Kamen Rider Zi-O joined Lupinranger VS Patranger on the Super Hero Time block."},
            {"Kamen Rider Zi-O", "Kamen Rider Heisei 20th", "https://vignette.wikia.nocookie.net/kamenrider/images/7/73/Zi-O_Logo.png/revision/latest?cb=20180807134901","https://vignette.wikia.nocookie.net/kamenrider/images/d/d6/Zi-O_Poster.png/revision/latest?cb=20180807153259", "September 2, 2018 - Now", "49 Episodes","Toei Company", "Kamen Rider Zi-O (仮面ライダージオウ Kamen Raidā Jiō) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series. It is the twentieth and final series in the Heisei period run, the first series to be produced in the Reiwa period, and the twenty-ninth series overall. The series started on September 2, 2018, joining Kaitou Sentai Lupinranger VS Keisatsu Sentai PatrangerIcon-crosswiki in the Super Hero Time line-up after the finale of Kamen Rider Build. After Lupinranger VS Patranger’s conclusion, it was joined by 4 Week Continuous Special Super Sentai Strongest Battle!!Icon-crosswiki in February 2019 and later Kishiryu Sentai RyusoulgerIcon-crosswiki in March 2019. After the finale of Kamen Rider Zi-O, Kamen Rider Zero-One will join Ryusoulger in Super Hero Time block."}
    };

    public static ArrayList<KamenRider> getListData(){
        KamenRider kamenrider = null;
        ArrayList<KamenRider> list = new ArrayList<>();
        for (String[] aData : data) {
            kamenrider = new KamenRider();
            kamenrider.setName(aData[0]);
            kamenrider.setHeisei(aData[1]);
            kamenrider.setLogo(aData[2]);
            kamenrider.setPhoto(aData[3]);
            kamenrider.setRealese(aData[4]);
            kamenrider.setTotaleps(aData[5]);
            kamenrider.setProducer(aData[6]);
            kamenrider.setDesc(aData[7]);

            list.add(kamenrider);
        }

        return list;
    }
}
